server:
  port: 11234
src:
  dns:
    max-line: 20000
    executor: 4
    bak: true
    category: dns

node:
  home: D:/gaea-bin
  src-path: D:/data/src
  data-path: D:/data
  category: dns
  name: test

