server:
  port: 11234
mongodb:
  pro:
    host: 172.16.1.102
    port: 27017
    user: tincery
    password: Txy123.com
    database: simulation_pro
  sys:
    host: 172.16.1.102
    port: 27017
    user: tincery
    password: Txy123.com
    database: simulation_sys
src:
  dns:
    max-line: 20000
    executor: 4
    bak: true
    category: dns

node:
  home: D:/gaea-bin
  src-path: D:/data/src
  data-path: D:/data
  category: dns
  name: test
logging:
  level:
    root: info

