server:
  port: 11236
spring:
  activemq:
    broker-url: tcp://172.16.1.101:61616
    user: admin
    password: admin
  application:
    name: src_session
mongodb:
  pro:
    host: 172.16.1.103,172.16.1.111
    port: 23000
    user: tincery
    password: Txy123.com
    database: tincery_pro
  sys:
    host: 172.16.1.103,172.16.1.111
    port: 23000
    user: tincery
    password: Txy123.com
    database: tincery_sys
node:
  category: controller
  home: /Users/gongxuanzhang/workSpace/support
  name: test
  src-path: /Users/gongxuanzhang/workSpace/support/src
logging:
  level:
    root: info
nacos:
  config:
    server-addr: 172.16.1.102:8848
