server:
  port: 11234
mongodb:
  pro:
    host: 172.16.1.102
    port: 27017
    user: tincery
    password: Txy123.com
    database: simulation_pro
  sys:
    host: 172.16.1.102
    port: 27017
    user: tincery
    password: Txy123.com
    database: simulation_sys
src:
  ssl:
    max-line: 20000
    executor: 4
    bak: true
spring:
  activemq:
    broker-url: tcp://172.16.1.101:61616
    user: admin
    password: admin
node:
  home: D:/gaea-bin
  name: insomnia
  src-path: D:/data/src
  data-path: D:/data
logging:
  level:
    root: info
