server:
  port: 11234
mongodb:
  pro:
    host: 172.16.1.102
    port: 27017
    user: tincery
    password: Txy123.com
    database: simulation_pro
  sys:
    host: 172.16.1.102
    port: 27017
    user: tincery
    password: Txy123.com
    database: simulation_sys
src:
  ssl:
    max-line: 20000
    executor: 4
    bak: true

node:
  home: /Users/gongxuanzhang/workSpace/support
  name: insomnia
  src-path: /Users/gongxuanzhang/workSpace/support/src
  data-path: /Users/gongxuanzhang/workSpace/support
  category: reorganization
logging:
  level:
    root: info
