server:
  port: 11234

node:
  home: /Users/gongxuanzhang/workSpace/support
  src-path: /Users/gongxuanzhang/workSpace/support/src
  data-path: /Users/gongxuanzhang/workSpace/support
  name: test

src:
  session:
    category: session
    max-line: 20000
    executor: 4
    bak: true