server:
  port: 11234
mongodb:
  pro:
    host: 172.16.1.103,172.16.1.111
    port: 23000
    user: tincery
    password: Txy123.com
    database: tincery_pro
  sys:
    host: 172.16.1.103,172.16.1.111
    port: 23000
    user: tincery
    password: Txy123.com
    database: tincery_sys
src:
  ssl:
    max-line: 20000
    executor: 4
    bak: true
    src-path: /Users/gongxuanzhang/workSpace/support/src/
category: session

node:
  home: /Users/gongxuanzhang/workSpace/support
  category: session
  name: 我来康康我叫什么sr
spring:
  application:
    name: gaea-src-session
logging:
  level:
    root: info
